import { combatFraming,createCombatCamera,applyCombatCamera } from './camera.mjs';
import * as THREE from '../libs/three.module.js';
import { RULES,geometry,movePlayer,wrap } from './combat.mjs';
import { aimTank } from './presentation.mjs';
export class RankedView {
 cameraFollow=createCombatCamera();
 constructor({scene,camera,renderer,buildTank,buildShot,disposeTank,controls,client,onEffect}){Object.assign(this,{scene,camera,renderer,buildTank,buildShot,disposeTank,controls,client,onEffect});this.meshes=new Map();this.shots=new Map();this.geo=new THREE.SphereGeometry(.22,8,6);this.materials=[new THREE.MeshBasicMaterial({color:0xe5f995}),new THREE.MeshBasicMaterial({color:0xff9269})];this.acc=0;this.pending=[];this.aimLine=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3()]),new THREE.LineBasicMaterial({color:0xe3eab7,transparent:true,opacity:.6}));}
 begin(m){this.clear();this.scene.add(this.aimLine);this.you=m.you;this.names=m.names;this.map=geometry(m.map);this.latest=m;for(const p of m.players){const mesh=this.buildTank(m.appearances?.[p.id],p.id===this.you);this.scene.add(mesh);const ring=new THREE.Mesh(new THREE.RingGeometry(1.4,1.52,40),this.materials[p.id===this.you?0:1]);ring.rotation.x=-Math.PI/2;ring.position.y=.08;ring.scale.setScalar(1/mesh.scale.x);mesh.add(ring);const canvas=document.createElement('canvas');canvas.width=128;canvas.height=32;const texture=new THREE.CanvasTexture(canvas),label=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,depthWrite:false,depthTest:false}));label.scale.set(2.7/mesh.scale.x,.675/mesh.scale.y,1);label.position.y=3.2/mesh.scale.y;mesh.add(label);mesh.userData.health={canvas,texture,label,hp:-1};this.meshes.set(p.id,mesh);}this.receive(m);}
 receive(m){if(m.id!==this.latest?.id)return;this.latest=m;const me=m.players.find(p=>p.id===this.you);this.client.seq=Math.max(this.client.seq,me.seq);this.predicted={...me};this.pending=this.pending.filter(i=>i.seq>me.seq);for(const i of this.pending)movePlayer(this.predicted,i,1/RULES.hz,this.map.walls);for(const ev of m.events||[]){if(ev.t==='fire'){const mesh=this.meshes.get(ev.id);if(mesh)mesh.userData.kick=.12;}this.onEffect(ev,ev.id===this.you);}}
 frame(dt){if(!this.latest||!this.predicted)return;const input=this.controls.read();this.acc+=Math.min(dt,.1);while(this.acc>=1/RULES.hz){this.acc-=1/RULES.hz;const i={...input,seq:++this.client.seq};this.client.send({t:'input',...i});this.pending.push(i);if(this.pending.length>60)this.pending.shift();movePlayer(this.predicted,i,1/RULES.hz,this.map.walls);}
  for(const p of this.latest.players){const mesh=this.meshes.get(p.id),target=p.id===this.you?this.predicted:p,k=p.id===this.you?1:1-Math.exp(-18*dt);mesh.visible=p.alive;mesh.position.x+=(target.x-mesh.position.x)*k;mesh.position.z+=(target.z-mesh.position.z)*k;mesh.rotation.y+=wrap(target.a-mesh.rotation.y)*k;aimTank(mesh,p.id===this.you?input.aim:p.aim,mesh.rotation.y);const kick=mesh.userData.kick=Math.max(0,(mesh.userData.kick||0)-dt);mesh.rotation.x=-kick*.25;const health=mesh.userData.health;if(health.hp!==p.hp){health.hp=p.hp;const c=health.canvas.getContext('2d');c.clearRect(0,0,128,32);c.fillStyle='#172125';c.fillRect(0,0,128,32);for(let i=0;i<3;i++){c.fillStyle=i<p.hp?(p.id===this.you?'#d4e88b':'#ff9269'):'#475356';c.fillRect(7+i*40,8,34,16);}health.texture.needsUpdate=true;}}
  const ids=new Set();for(const b of this.latest.bullets){ids.add(b.id);let mesh=this.shots.get(b.id);if(!mesh){mesh=this.buildShot?.(b.owner===this.you)||new THREE.Mesh(this.geo,this.materials[b.owner===this.you?0:1]);this.scene.add(mesh);this.shots.set(b.id,mesh);}mesh.position.set(b.x,1.2,b.z);mesh.rotation.y=Math.atan2(-b.vx,-b.vz);}
  for(const [id,m] of this.shots)if(!ids.has(id)){this.scene.remove(m);this.shots.delete(id);}
  const p=this.predicted;const a=this.aimLine.geometry.attributes.position;a.setXYZ(0,p.x,1.3,p.z);a.setXYZ(1,p.x-Math.sin(input.aim)*4,1.3,p.z-Math.cos(input.aim)*4);a.needsUpdate=true;this.aimLine.visible=p.alive;
  const framing=combatFraming(innerWidth,innerHeight,true),focus=this.cameraFollow.update({x:p.x,z:p.z,input,framing,dt,alive:p.alive,limit:24.25,reducedMotion:!!this.reducedMotion?.()});
  applyCombatCamera(this.camera,focus,framing);
  const w=innerWidth,h=innerHeight,vw=Math.min(w,h*16/9),vh=vw*9/16;this.renderer.setScissorTest(false);this.renderer.setViewport(0,0,w,h);this.renderer.clear();this.renderer.setViewport((w-vw)/2,(h-vh)/2,vw,vh);this.renderer.setScissor((w-vw)/2,(h-vh)/2,vw,vh);this.renderer.setScissorTest(true);this.renderer.render(this.scene,this.camera);this.renderer.setScissorTest(false);this.renderer.setViewport(0,0,w,h);
 }
 clear(){this.cameraFollow.reset();this.scene.remove(this.aimLine);for(const mesh of this.meshes.values()){this.scene.remove(mesh);const h=mesh.userData.health;if(h){h.texture.dispose();h.label.material.dispose();h.label.removeFromParent();}const rings=[];mesh.traverse(o=>{if(o.geometry?.type==='RingGeometry')rings.push(o);});for(const r of rings){r.removeFromParent();r.geometry.dispose();}this.disposeTank(mesh);}for(const m of this.shots.values())this.scene.remove(m);this.meshes.clear();this.shots.clear();this.latest=null;this.pending=[];this.predicted=null;this.acc=0;}
}
