import test from 'node:test';
import assert from 'node:assert/strict';
import { RULES,inputOf,createMatch,acceptInput,step,finish,geometry,movePlayer,elo } from '../game/combat.mjs';
import { AccountStore } from '../net/store.mjs';
import { migratePremium,captureLoadout,restoreLoadout } from '../game/premium-profile.mjs';
import { ARENAS } from '../game/arenas.mjs';

test('competitive maps preserve three stable IDs, connected walkable cells and symmetry',()=>{
 assert.deepEqual(ARENAS.map(a=>a.id),[13,14,15]);for(const a of ARENAS){const n=a.grid.length;for(let r=0;r<n;r++)for(let c=0;c<n;c++)assert.equal(a.grid[r][c],a.grid[n-1-r][n-1-c]);const open=geometry(a.id).open;assert.ok(open.length>50);}
});
test('invalid, stale and repeated inputs cannot move a player',()=>{const m=createMatch('m',13,['a','b']);assert.equal(inputOf({seq:1,x:NaN,z:0,aim:0,fire:false}),null);assert.equal(inputOf({seq:1,x:0,z:0,aim:0,fire:'yes'}),null);assert.equal(acceptInput(m,'a',{seq:1,x:999,z:999,aim:0,fire:false}),true);assert.ok(Math.hypot(m.players[0].input.x,m.players[0].input.z)<=1.00001);assert.equal(acceptInput(m,'a',{seq:1,x:0,z:0,aim:0,fire:true}),false);assert.equal(acceptInput(m,'missing',{seq:2,x:0,z:0,aim:0,fire:false}),false);});
test('movement and projectiles are deterministic across cosmetic selections',()=>{const a=createMatch('same',14,['a','b']),b=createMatch('same',14,['a','b']);for(let n=0;n<300;n++){const input={seq:n,x:Math.sin(n/60),z:Math.cos(n/60),aim:n/30,fire:true};acceptInput(a,'a',input);acceptInput(b,'a',{...input,tank:'titan',speed:900,damage:99});step(a);step(b);}assert.deepEqual(a,b);});
test('input timeout stops movement and fire after a lost connection',()=>{const m=createMatch('m',13,['a','b']);acceptInput(m,'a',{seq:1,x:1,z:0,aim:0,fire:true});for(let i=0;i<20;i++)step(m);const x=m.players[0].x,n=m.nextBullet;for(let i=0;i<30;i++)step(m);assert.equal(m.players[0].x,x);assert.equal(m.nextBullet,n);});
test('server owns HP, cooldown, death, respawn and protection',()=>{const m=createMatch('m',13,['a','b']);m.geo.walls=[];Object.assign(m.players[0],{x:0,z:8,inv:0});Object.assign(m.players[1],{x:0,z:0,inv:0});for(let i=0;i<100;i++){acceptInput(m,'a',{seq:i,x:0,z:0,aim:0,fire:true});step(m);}assert.ok(m.players[0].score>=1);assert.ok(m.nextBullet<=8);assert.equal(RULES.hp,3);assert.ok(m.players[1].hp<=3);});
test('muzzle cannot fire through adjacent walls',()=>{const m=createMatch('m',13,['a','b']);m.geo.walls=[{x:0,z:0,h:2.25}];Object.assign(m.players[0],{x:0,z:3.51,inv:0});Object.assign(m.players[1],{x:0,z:-4,inv:0});for(let i=0;i<100;i++){acceptInput(m,'a',{seq:i,x:0,z:0,aim:0,fire:true});step(m);}assert.equal(m.players[1].hp,3);assert.equal(m.players[0].score,0);});
test('time limit, sudden death and final draw are bounded',()=>{const a=createMatch('a',13,['a','b']);a.time=179.99;a.players[0].score=1;step(a);assert.equal(a.winner,'a');const b=createMatch('b',13,['a','b']);b.time=179.99;step(b);assert.equal(b.over,false);b.time=209.99;step(b);assert.equal(b.over,true);assert.equal(b.winner,null);});
test('only two ricochets are allowed',()=>{const m=createMatch('m',13,['a','b']);m.geo.walls=[{x:-3,z:0,h:1},{x:3,z:0,h:1}];m.players.forEach(p=>p.alive=false);m.bullets=[{id:1,owner:'a',x:0,z:0,vx:24,vz:0,life:3,bounces:0}];for(let i=0;i<25;i++)step(m);assert.equal(m.bullets.length,0);});
test('match transaction is idempotent, awards both accounts and never imports legacy coins',async()=>{const store=new AccountStore(),a=await store.create('A'),b=await store.create('B');const m=createMatch('tx',13,[a.account.id,b.account.id]);finish(m,a.account.id,'target');const first=await store.commit(m),again=await store.commit(m);assert.deepEqual(first,again);assert.equal((await store.authenticate(a.token)).games,1);assert.equal((await store.authenticate(a.token)).credits,70);assert.equal(await store.authenticate('invalid'),null);assert.deepEqual(elo(1000,1000,.5),[1000,1000]);});
test('forfeit earns no credits, server void earns neither credits nor rating',async()=>{const store=new AccountStore(),a=await store.create('A'),b=await store.create('B');const m=createMatch('tx',13,[a.account.id,b.account.id]);finish(m,b.account.id,'disconnect');const r=await store.commit(m);assert.equal(r.players[a.account.id].reward,0);const v=createMatch('void',13,[a.account.id,b.account.id]);finish(v,null,'server');assert.equal(await store.commit(v),null);assert.equal((await store.authenticate(a.token)).games,1);});
test('premium migration preserves inventory and balances and loadouts cannot equip unowned items',()=>{const p={coins:1234,gems:6,owned:['recruit'],skins:['default'],selected:'recruit',skin:'default',upgrades:{recruit:{health:2}}};migratePremium(p);const initial=structuredClone(p);migratePremium(p);assert.deepEqual(p,initial);assert.equal(p.coins,1234);assert.equal(p.upgrades.recruit.health,2);const l=captureLoadout(p);restoreLoadout(p,{...l,selected:'titan',skin:'invalid'});assert.equal(p.selected,'recruit');assert.equal(p.skin,'default');assert.equal(p.loadouts.length,3);});

test('cosmetic purchase is atomic and duplicate retries debit once',async()=>{const store=new AccountStore(),a=await store.create('A');await store.update(a.account.id,row=>({...row,credits:1000}));await Promise.all(Array.from({length:10},()=>store.purchase(a.account.id,'decal:clawink')));const row=await store.authenticate(a.token);assert.equal(row.credits,850);assert.deepEqual(row.data.inventory,['decal:clawink']);await assert.rejects(store.purchase(a.account.id,'speed:advantage'));await store.purchase(a.account.id,'acc:holodrone');await assert.rejects(store.purchase(a.account.id,'projectile:football'));assert.equal((await store.authenticate(a.token)).credits,0);});
test('recovery codes are hashed, one-use, and invalidate the old session',async()=>{const store=new AccountStore(),a=await store.create('A');const {code}=await store.recovery(a.account.id);assert.notEqual((await store.authenticate(a.token)).recovery_hash,code);const recovered=await store.recover(code);assert.equal(recovered.account.id,a.account.id);assert.equal(await store.authenticate(a.token),null);assert.equal(await store.recover(code),null);assert.ok(await store.authenticate(recovered.token));});
